Add Openn311_ServiceRequest.
OkinawaOpenLaboratory/orion-spreadsheet-connector pull request #2
Opened 2021-06-09 05:08 UTC by TakashiAbe0309

I wrote a gas to register the data of Open311_ServiceRequest in Orion.

2021-06-09 05:54 UTC, YujiAzama requested changes

2021-06-09 05:54 UTC, YujiAzama commented on Open311_ServiceRequest/src/open311_ServiceRequest.gs
> +  var sheet = SpreadsheetApp.getActive().getSheetByName('Issues');
I think the sheet name should define the type of standard data model. (e.g. Open311ServiceRequest)

2021-06-09 05:54 UTC, YujiAzama commented on Open311_ServiceRequest/src/open311_ServiceRequest.gs
> +  var media_url = sheet.getRange(lastRow, 4).getValue();
You should use lowerCamelCase for local variables.

2021-06-09 05:54 UTC, YujiAzama commented on Open311_ServiceRequest/src/open311_ServiceRequest.gs
> +  var service_code = sheet.getRange(lastRow, 5);
ditto

2021-06-09 05:54 UTC, YujiAzama commented on Open311_ServiceRequest/src/open311_ServiceRequest.gs
> +  var service_name = sheet.getRange(lastRow, 6).getValue();
ditto

2021-06-11 01:12 UTC, TakashiAbe0309 reviewed
I fixed what was pointed out in the review.
I changed the sheet name of the script from Issues to Open311ServiceRequest.
I modified the local variable of the script to lowerCamelCase.

2021-06-11 01:12 UTC, TakashiAbe0309 commented on Open311_ServiceRequest/src/open311_ServiceRequest.gs
> +  var sheet = SpreadsheetApp.getActive().getSheetByName('Issues');
Thank you for the review.
I change the spreadsheet name from Issues to Open311ServiceRequest.

2021-06-11 01:12 UTC, TakashiAbe0309 commented on Open311_ServiceRequest/src/open311_ServiceRequest.gs
> +  var media_url = sheet.getRange(lastRow, 4).getValue();
Thank you for the review. I fix the pointed-out part.

2021-06-12 14:14 UTC, YujiAzama approved these changes
LGTM

2021-06-12 14:14 UTC, merged